Nambahin fungsi buat bersihin nama gereja dan sekolah
pmk-itb/api-pmb pull request #30
Opened 2021-08-10 17:40 UTC by AdrianTimotheus

## Type of Changes

- [ ] Bug fix
- [x] New feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe below

## Breaking Changes

Is there any breaking changes introduced by this PR?

- [ ] Yes
- [x] No

If yes, please describe below:

## Description

## Checklist

- [ ] I have added new tests to cover my changes
- [ ] All new and existing tests are passing

2021-08-11 09:51 UTC, stefanusgusega requested changes

2021-08-11 09:51 UTC, stefanusgusega commented on src/sanitization.ts
> +export let formatName = (inputName) =>{
dikasih type ian, jgn lupa soalnya ini typescript, contoh
```typescript
export let formatName = (inputName: string) => ...
```

2021-08-11 09:51 UTC, stefanusgusega commented on src/sanitization.ts
> +export let formatTelp = (no_telp) => {
ini juga dikasih type yaa

2021-08-11 09:51 UTC, stefanusgusega commented on src/sanitization.ts
> +export let formatSekolah = (sekolah) => {
ini juga dikasih type

2021-08-11 09:51 UTC, stefanusgusega commented on src/sanitization.ts
> +export let formatGereja = (gereja) => {
ini dikasih type juga yaa

2021-08-15 05:29 UTC, stefanusgusega requested changes
bisa ditambahin testcase gaa ian?

2021-08-15 05:35 UTC, AdrianTimotheus commented
oke fan gw lagi bikin testcasenya skrg

2021-08-22 06:51 UTC, merged